### ISSUE TITLE
Errors with twt on Snow Leopard / zsh

### ISSUE THREAD

**Issue by ccuq** [pbosetti/twt#1]
[10:15][christophe@lienragcuqorg] /Users/christophe -%> twt user
SHOWING LAST UNREAD USER_TIMELINE MESSAGES:
/Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:60:in `color': Wrong text color friends (ArgumentError)
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:192:in`query'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:180:in `each'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:180:in`query'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:345
        from /usr/bin/twt:19:in `load'
        from /usr/bin/twt:19
[14:30][christophe@lienragcuqorg] /Users/christophe -%> twt friends
SHOWING LAST UNREAD FRIENDS_TIMELINE MESSAGES:
/Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:60:in`color': Wrong text color friends (ArgumentError)
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:192:in `query'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:180:in`each'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:180:in `query'
        from /Library/Ruby/Gems/1.8/gems/twt-0.2.1/bin/twt:347
        from /usr/bin/twt:19:in`load'
        from /usr/bin/twt:19
[14:31][christophe@lienragcuqorg] /Users/christophe -%> twt delta  
Last time followers: 70
Now you have 72 follower(s)
New followers (2):
  @Mat_A: Mathieu Arnold
  @atchikservices: atchikservices
Lost followers (0):
  none
[14:31][christophe@lienragcuqorg] /Users/christophe -%>

**Comment by ccuq** [comment]
Problem solved. I sent a wrong command and the "color" option is sticky... (twt -k friends => and it stored the "friend" as color parameter...

Giving a new good value solved me.

Sorry for the noise.

**Comment by pbosetti** [comment]
You're welcome! perhaps I'd have to reject wrong color values instead of storing them in ~/.twitter/cfg.yaml. I'll do it in next version.
