### ISSUE TITLE
oauth errors?

### ISSUE THREAD

**Issue by rockpapergoat** [pbosetti/twt#2]
on a couple of systems (os x, centos), i'm seeing this on connection:

twt:119:in `connect': undefined method`new' for Twitter::Authentication:Module (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/twt-0.2.7/bin/twt:172:in `query'
    from /Library/Ruby/Gems/1.8/gems/twt-0.2.7/bin/twt:391
    from /usr/bin/twt:19:in`load'
    from /usr/bin/twt:19

i have these gem versions installed on os x:

twitter (1.6.2, 1.4.1)
twitter_oauth (0.4.3)
twt (0.2.7)

plus:

rubygems (1.8.2)
ruby (1.8.7, p174)

i'm guessing twitter oauth changes renamed or removed methods. is that the case?

**Comment by pbosetti** [comment]
Thanks for the head up. I'm on vacation now, I'll check it next week. 

-P.

Il giorno 26/ago/2011, alle ore 05:57, rockpapergoatreply@reply.github.com ha scritto:

**Comment by pbosetti** [comment]
I just pushed twt v0.3.0, with updated OAuth method that should work fine now. Let me know.
-P.

On Aug 26, 2011, at 4:57 AM, rockpapergoat wrote:

> on a couple of systems (os x, centos), i'm seeing this on connection:
> 
> twt:119:in `connect': undefined method`new' for Twitter::Authentication:Module (NoMethodError)
>   from /Library/Ruby/Gems/1.8/gems/twt-0.2.7/bin/twt:172:in `query'
>   from /Library/Ruby/Gems/1.8/gems/twt-0.2.7/bin/twt:391
>   from /usr/bin/twt:19:in`load'
>   from /usr/bin/twt:19
> 
> i have these gem versions installed on os x:
> 
> twitter (1.6.2, 1.4.1)
> twitter_oauth (0.4.3)
> twt (0.2.7)
> 
> plus:
> 
> rubygems (1.8.2)
> ruby (1.8.7, p174)
> 
> i'm guessing twitter oauth changes renamed or removed methods. is that the case?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pbosetti/twt/issues/2

---

Paolo Bosetti
web: http://punz.posterous.com
     http://flic.kr/pbosetti
twitter: @P4010

**Comment by rockpapergoat** [comment]
looks good, paolo! the version string is still 0.2.7, but oauth works again.
